export const mockCompanies = [
  {
    id: 'cmp-001',
    name: 'Instituto Horizonte',
    industry: 'Educación',
    contactEmail: 'contacto@horizonte.edu.mx',
    activeTickets: 4,
  },
  {
    id: 'cmp-002',
    name: 'Grupo TecnoAvanza',
    industry: 'Tecnología',
    contactEmail: 'soporte@tecnoavanza.com',
    activeTickets: 3,
  },
  {
    id: 'cmp-003',
    name: 'Universidad del Norte',
    industry: 'Educación',
    contactEmail: 'helpdesk@uninorte.mx',
    activeTickets: 2,
  },
  {
    id: 'cmp-004',
    name: 'Salud Integral',
    industry: 'Salud',
    contactEmail: 'mesa@saludintegral.org',
    activeTickets: 1,
  },
]

export const mockUsers = [
  {
    id: 'usr-1001',
    name: 'Ana Martínez',
    email: 'ana.martinez@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'active',
    lastLogin: 'Hoy 09:10',
  },
  {
    id: 'usr-1002',
    name: 'Carlos Gómez',
    email: 'carlos.gomez@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'active',
    lastLogin: 'Ayer 18:22',
  },
  {
    id: 'usr-1003',
    name: 'Laura Hernández',
    email: 'laura.hernandez@uninorte.mx',
    companyId: 'cmp-003',
    companyName: 'Universidad del Norte',
    status: 'locked',
    lastLogin: 'Hace 3 días',
  },
  {
    id: 'usr-1004',
    name: 'Miguel Torres',
    email: 'miguel.torres@saludintegral.org',
    companyId: 'cmp-004',
    companyName: 'Salud Integral',
    status: 'active',
    lastLogin: 'Hoy 07:45',
  },
  {
    id: 'usr-1005',
    name: 'Sofía López',
    email: 'sofia.lopez@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'pending',
    lastLogin: 'Hace 5 días',
  },
  {
    id: 'usr-1006',
    name: 'Diego Ruiz',
    email: 'diego.ruiz@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'active',
    lastLogin: 'Hoy 08:30',
  },
]

export const mockTickets = [
  {
    id: 'tck-9001',
    folio: 'EVA-2024-0901',
    subject: 'No puedo iniciar sesión desde móvil',
    message: 'El acceso desde la app móvil se queda en pantalla en blanco.',
    userName: 'Ana Martínez',
    userEmail: 'ana.martinez@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'open',
    priority: 'high',
    createdAt: '2024-02-10T09:15:00Z',
    updatedAt: '2024-02-10T10:02:00Z',
    tags: ['login', 'mobile'],
    lastAgentResponseAt: '2024-02-10T09:45:00Z',
    channel: 'web',
    attachments: [{ name: 'screenshot-login.png', url: '#', size: '2.4 MB' }],
  },
  {
    id: 'tck-9002',
    folio: 'EVA-2024-0902',
    subject: 'Actualizar correo en certificado',
    message: 'El correo en mi certificado está incorrecto, necesito corregirlo.',
    userName: 'Carlos Gómez',
    userEmail: 'carlos.gomez@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'pending',
    priority: 'medium',
    createdAt: '2024-02-09T16:40:00Z',
    updatedAt: '2024-02-10T08:20:00Z',
    tags: ['certificados'],
    lastAgentResponseAt: '2024-02-10T08:05:00Z',
    channel: 'email',
    attachments: [],
  },
  {
    id: 'tck-9003',
    folio: 'EVA-2024-0903',
    subject: 'Recuperación de contraseña',
    message: 'No recibo el correo de recuperación de contraseña.',
    userName: 'Laura Hernández',
    userEmail: 'laura.hernandez@uninorte.mx',
    companyId: 'cmp-003',
    companyName: 'Universidad del Norte',
    status: 'solved',
    priority: 'low',
    createdAt: '2024-02-08T11:10:00Z',
    updatedAt: '2024-02-08T14:32:00Z',
    tags: ['password'],
    lastAgentResponseAt: '2024-02-08T14:10:00Z',
    channel: 'email',
    attachments: [],
  },
  {
    id: 'tck-9004',
    folio: 'EVA-2024-0904',
    subject: 'Examen se queda cargando',
    message: 'El examen se queda cargando al enviar las respuestas finales.',
    userName: 'Miguel Torres',
    userEmail: 'miguel.torres@saludintegral.org',
    companyId: 'cmp-004',
    companyName: 'Salud Integral',
    status: 'open',
    priority: 'high',
    createdAt: '2024-02-10T07:20:00Z',
    updatedAt: '2024-02-10T09:05:00Z',
    tags: ['exams', 'performance'],
    lastAgentResponseAt: '2024-02-10T08:40:00Z',
    channel: 'whatsapp',
    attachments: [{ name: 'log.txt', url: '#', size: '350 KB' }],
  },
  {
    id: 'tck-9005',
    folio: 'EVA-2024-0905',
    subject: 'Validación de pago pendiente',
    message: 'El pago del voucher aparece pendiente desde ayer.',
    userName: 'Sofía López',
    userEmail: 'sofia.lopez@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'pending',
    priority: 'medium',
    createdAt: '2024-02-09T13:55:00Z',
    updatedAt: '2024-02-10T08:10:00Z',
    tags: ['pagos', 'vouchers'],
    lastAgentResponseAt: '2024-02-09T18:40:00Z',
    channel: 'web',
    attachments: [],
  },
  {
    id: 'tck-9006',
    folio: 'EVA-2024-0906',
    subject: 'Error al cargar certificado',
    message: 'No puedo descargar el certificado, muestra error 500.',
    userName: 'Diego Ruiz',
    userEmail: 'diego.ruiz@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'open',
    priority: 'high',
    createdAt: '2024-02-10T06:05:00Z',
    updatedAt: '2024-02-10T06:40:00Z',
    tags: ['certificados', 'descarga'],
    lastAgentResponseAt: '2024-02-10T06:25:00Z',
    channel: 'email',
    attachments: [],
  },
  {
    id: 'tck-9007',
    folio: 'EVA-2024-0907',
    subject: 'Acceso restringido por rol',
    message: 'El usuario no puede ver su historial de resultados.',
    userName: 'Mariana Vega',
    userEmail: 'mariana.vega@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'pending',
    priority: 'low',
    createdAt: '2024-02-07T17:22:00Z',
    updatedAt: '2024-02-09T11:05:00Z',
    tags: ['roles', 'permisos'],
    lastAgentResponseAt: '2024-02-09T10:50:00Z',
    channel: 'web',
    attachments: [],
  },
  {
    id: 'tck-9008',
    folio: 'EVA-2024-0908',
    subject: 'Reporte de error en telemetría',
    message: 'El panel de telemetría marca 0% uptime.',
    userName: 'Luis Paredes',
    userEmail: 'luis.paredes@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'open',
    priority: 'medium',
    createdAt: '2024-02-09T19:50:00Z',
    updatedAt: '2024-02-10T07:10:00Z',
    tags: ['telemetria'],
    lastAgentResponseAt: '2024-02-10T07:05:00Z',
    channel: 'email',
    attachments: [],
  },
  {
    id: 'tck-9009',
    folio: 'EVA-2024-0909',
    subject: 'Solicitan agregar nuevo plantel',
    message: 'Necesitamos agregar un nuevo campus para el siguiente grupo.',
    userName: 'Julia Ríos',
    userEmail: 'julia.rios@uninorte.mx',
    companyId: 'cmp-003',
    companyName: 'Universidad del Norte',
    status: 'solved',
    priority: 'low',
    createdAt: '2024-02-06T10:05:00Z',
    updatedAt: '2024-02-07T08:40:00Z',
    tags: ['partners', 'campus'],
    lastAgentResponseAt: '2024-02-07T08:15:00Z',
    channel: 'email',
    attachments: [],
  },
  {
    id: 'tck-9010',
    folio: 'EVA-2024-0910',
    subject: 'WhatsApp no responde',
    message: 'El canal WhatsApp no está respondiendo mensajes automáticos.',
    userName: 'Fernando Silva',
    userEmail: 'fernando.silva@saludintegral.org',
    companyId: 'cmp-004',
    companyName: 'Salud Integral',
    status: 'pending',
    priority: 'medium',
    createdAt: '2024-02-09T21:30:00Z',
    updatedAt: '2024-02-10T08:30:00Z',
    tags: ['whatsapp', 'automatizacion'],
    lastAgentResponseAt: '2024-02-10T08:10:00Z',
    channel: 'whatsapp',
    attachments: [{ name: 'chat-log.pdf', url: '#', size: '1.1 MB' }],
  },
  {
    id: 'tck-9011',
    folio: 'EVA-2024-0911',
    subject: 'Consulta sobre resultados',
    message: 'No veo mis resultados del examen de ayer.',
    userName: 'Paola Jiménez',
    userEmail: 'paola.jimenez@horizonte.edu.mx',
    companyId: 'cmp-001',
    companyName: 'Instituto Horizonte',
    status: 'open',
    priority: 'low',
    createdAt: '2024-02-10T05:30:00Z',
    updatedAt: '2024-02-10T07:25:00Z',
    tags: ['resultados'],
    lastAgentResponseAt: '2024-02-10T06:55:00Z',
    channel: 'web',
    attachments: [],
  },
  {
    id: 'tck-9012',
    folio: 'EVA-2024-0912',
    subject: 'Error al cargar contenido',
    message: 'Los materiales de estudio no cargan en Chrome.',
    userName: 'Ricardo Valdez',
    userEmail: 'ricardo.valdez@tecnoavanza.com',
    companyId: 'cmp-002',
    companyName: 'Grupo TecnoAvanza',
    status: 'open',
    priority: 'medium',
    createdAt: '2024-02-09T08:15:00Z',
    updatedAt: '2024-02-10T08:05:00Z',
    tags: ['study-contents', 'browser'],
    lastAgentResponseAt: '2024-02-10T08:00:00Z',
    channel: 'web',
    attachments: [],
  },
]
