export const mockTickets = [
  {
    id: 'SUP-1001',
    user: 'Ana Martínez',
    email: 'ana.martinez@demo.com',
    status: 'open',
    priority: 'high',
    createdAt: 'Hace 10 min',
    message: 'No puedo iniciar sesión en la plataforma desde el móvil.',
  },
  {
    id: 'SUP-1002',
    user: 'Carlos Gómez',
    email: 'carlos.gomez@demo.com',
    status: 'pending',
    priority: 'medium',
    createdAt: 'Hace 25 min',
    message: 'Necesito actualizar mi correo asociado al certificado.',
  },
  {
    id: 'SUP-1003',
    user: 'Laura Hernández',
    email: 'laura.hernandez@demo.com',
    status: 'solved',
    priority: 'low',
    createdAt: 'Hace 1 h',
    message: 'Solicitud de recuperación de contraseña resuelta.',
  },
  {
    id: 'SUP-1004',
    user: 'Miguel Torres',
    email: 'miguel.torres@demo.com',
    status: 'open',
    priority: 'high',
    createdAt: 'Hace 2 h',
    message: 'El examen se quedó en pantalla blanca al enviar respuestas.',
  },
  {
    id: 'SUP-1005',
    user: 'Sofía López',
    email: 'sofia.lopez@demo.com',
    status: 'pending',
    priority: 'medium',
    createdAt: 'Ayer',
    message: 'Validación de pago pendiente para voucher de evaluación.',
  },
  {
    id: 'SUP-1006',
    user: 'Diego Ruiz',
    email: 'diego.ruiz@demo.com',
    status: 'solved',
    priority: 'low',
    createdAt: 'Hace 2 días',
    message: 'Ticket cerrado después de actualizar datos personales.',
  },
]
